# Generated by Django 4.2.4 on 2023-08-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApi', '0003_deliverycrew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data',
            new_name='date',
        ),
    ]
