# Generated by Django 4.2.4 on 2023-08-23 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApi', '0005_alter_order_delivery_crew_alter_order_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverycrew',
            old_name='item',
            new_name='orderId',
        ),
    ]
