# Generated by Django 4.2.4 on 2023-08-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApi', '0007_alter_deliverycrew_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycrew',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
