# Generated by Django 4.2.4 on 2023-08-23 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantApi', '0008_alter_deliverycrew_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverycrew',
            old_name='delivery',
            new_name='delivery_crew',
        ),
        migrations.RenameField(
            model_name='deliverycrew',
            old_name='orderId',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_crew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='deliverycrew',
            unique_together={('user', 'delivery_crew')},
        ),
    ]
